<?php 
include _include(ADMIN_PATH.'view/htm/header.inc.htm');
$settings = getConfig()
?>
<link rel="stylesheet" href="/plugin/sl_repeat_follow/view/farbtastic.css" type="text/css" />
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <form action="<?php echo url("plugin-setting-sl_repeat_follow");?>" method="post" id="form">

                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">每页显示数量：</label>
                        <div class="col-sm-10">
                            <?=form_text('ppg', $settings[peerPage], 100); ?>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">宽度（百分比）：</label>
                        <div class="col-md-3">
                            <div class="input-group mb-1">
                                <?php echo form_text('b_w', $settings[width], 100); ?>
                                <div class="input-group-prepend"><span class="input-group-text">0为自动</span></div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group mb-1">
                                <div class="input-group-prepend"><span class="input-group-text">最小</span></div>
                                <?php echo form_text('b_mw', $settings[minWidth], 100); ?>
                                <div class="input-group-prepend"><span class="input-group-text">像素（px）</span></div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">背景颜色：</label>
                        <div class="col-md-3">
                            <div class="input-group mb-1">
                                <?php echo form_text('color', $settings[backgroundColor], 100); ?>
                            </div>
                            <div id="picker"></div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">显示下划线：</label>
                        <div class="col-md-5">
                            <div class="input-group mb-1">
                                <?php echo form_text('b_c', $settings[backgroundColor], 100); ?>
                                <?php $line_style= $settings[lineStyle];  ?>
                                <select name="b_t" id="b_t" class="form-control">
                                    <option value="0" >禁用</option>
                                    <option value="solid">实线————————</option>
                                    <option value="dashed">虚线----------------</option>
                                    <option value="dotted">点线................</option>
                                </select>
                            </div>
                            <div id="picker2"></div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label"></label>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary btn-block" id="submit" data-loading-text="<?php echo lang('submiting');?>..."><?php echo lang('confirm');?></button>
                            <a role="button" class="btn btn-secondary btn-block mt-3" href="javascript:history.back();"><?php echo lang('back');?></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<?php include _include(ADMIN_PATH.'view/htm/footer.inc.htm');?>
<script type="text/javascript" src="/plugin/sl_repeat_follow/view/js/farbtastic.js"></script>
<link rel="stylesheet" href="/plugin/sl_repeat_follow/view/farbtastic.css" type="text/css" />
<script type="text/javascript" charset="utf-8">

    $(document).ready(()=> {
        $('#picker').farbtastic('#color');
        $('#picker2').farbtastic('#b_c');
        $("option[value=<?= $settings[lineStyle] ?>]").prop("selected",true)
    });

</script>