<?php
$r_uid = $repeat_follow['uid'];
$del = $del ?? $r_uid==$uid || $_post['floormanage'];
$usn = $repeat_follow['username'];
$t_uid = $repeat_follow['t_uid'];
$t_usn = $repeat_follow['t_username'];
$fl = $repeat_follow['fl'];
$time = humandate($repeat_follow['update']);
$a_url = $repeat_follow['avatar_url'];
?>
<dd class="text-left media" id="pf_<?=$pid?>_<?=$fl?>">
    <a href="<?= url("user-".$r_uid) ?>" class="mr-2">
        <img class="avatar-3" src="<?=$a_url?>">
    </a>
    <div style="width:100%;">
        <span class="text-left">
            <a href="<?= url("user-".$r_uid)?>" class="text-muted font-weight-bold"><?= $usn?></a>
            :<?php if($r_uid>0 && $t_usn!='') { ?>
                回复 <a href="<?= url("user-".$r_uid) ?>" class="text-muted font-weight-bold"><?= $t_usn?></a>:
            <?php } echo $repeat_follow['message'] ?>
        </span>
        <div class="text-muted text-right">
            <?=$time?>
            <?php if ($del) { ?> <a href="javascript:delrfloor('<?=$pid?>','<?=$fl?>');" class="post_update mr-2">删除</a> <?php } ?>
            <a href="javascript:showform('<?=$pid?>','<?=$usn?>');" class="post_update ml-2">回复</a>
        </div>
    </div>
</dd>